### PR TITLE
Add TOML Config File Feature

### PR DESCRIPTION
**Pull request by alikhan1998**
**/Ready for Review**

**Purpose:**
This Pull Request introduces the TOML config file feature to enhance the flexibility and user-friendliness of the CLI application. The need for a configuration file arises from the desire to allow users to specify options more conveniently and store preferences persistently.

**Key Changes:**
- Added support for parsing TOML config files.
- Implemented command-line option to specify the config file path.
- Integrated TOML parsing library for reliable configuration data handling.

**Context:**
This enhancement is in line with the project's goal to streamline configuration management and improve the user experience. It addresses [issue link], where users requested the ability to use config files.

**Note:**
This Pull Request is marked as a "Draft" to indicate that further refinements and testing may be necessary. Your feedback and suggestions are welcome as we work towards the final implementation.

### CODE REVIEW

**Comment by alikhan1998** [comment]
WangGithub0
Please note that I've completed my work on this feature. Could you please review and test the code? Thank you!

**Comment by WangGithub0** [comment]
@alikhan1998 thanks for your PR, could you provide a Config File example?

**Comment by alikhan1998** [comment]
# This is a TOML configuration file example

# Server settings
[server]
port = 8080
hostname = "example.com"

# Database settings
[database]
host = "db.example.com"
port = 5432
username = "myuser"
password = "mypassword"
database_name = "mydb"

# Logging settings
[logging]
level = "info"
file_path = "/var/log/myapp.log"

**Comment by WangGithub0** [comment]
@alikhan1998  could you add a file in the project, and also revise the README

**Comment by WangGithub0** [comment]
@alikhan1998  my main usage is  java src/ConvertTxtToHtml.java <path-to-txt-file>
could you provide me how to combine your code and my old part? thanks

**Review by humphd — CHANGES_REQUESTED** [review]
This is Python code, I'm unclear why you're submitting it when the project is written in Java.

Please fix your PR to use the proper language.

**Comment by alikhan1998** [comment]
I have done all the changes. Kindly recheck it

**Comment by WangGithub0** [comment]
@alikhan1998  I can't find --config in the src/ConvertTxtToHtml.java file in your PR.

**Pull request closed without merging**
